url: 'https://muzeum.grebocin.pl'
name: 'Muzeum Piśmiennictwa i Drukarstwa w Grębocinie'
description: 'Muzeum Piśmiennictwa i Drukarstwa w zabytkowym gotyckim kościele. Prezentujemy zabytkowe prasy drukarskie i unikatowe zbiory. Prowadzimy warsztaty i pokazy.'
